name: Lipo_MF_Model
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.11
  - pytorch::pytorch>=2.1
  - aimsim
  - argparse
  - configargparse
  - lightning>=2.0
  - numpy<2.0
  - pandas
  - rdkit
  - scikit-learn
  - scipy